name = "sigsmail"
main = "worker/src/index.ts"

# 打包配置
minify = true
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-03-27"
keep_vars = true

# 启用 D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "sigsma-mail-db"
database_id = "67d771dc-4638-46c9-8e2d-3d58a14a2fea"
# fix: 将迁移目录直接配置在这里，这是 D1 自动迁移的标准做法
migrations_dir = "worker/drizzle"

# 定义环境变量和密钥
[vars]
PASSWORD = "SIGSMA"
COOKIES_SECRET = "x7K9$mP2vL5qR8#nW3bY6!jC4*zT1@fH"
EMAIL_DOMAIN = "sigsmawproject.biz.id"
SEND_CHANNEL = ""
SENDER_EMAIL = ""
SEND_RATE_LIMIT_PER_MINUTE = ""
SEND_IP_RATE_LIMIT_PER_MINUTE = ""
TURNSTILE_KEY = ""
TURNSTILE_SECRET = ""
API_RATE_LIMIT_PER_MINUTE = ""
SHOW_AFF = ""
ENABLE_OPENAPI = "false"

# Cloudflare 原生邮件发送绑定
[[send_email]]
name = "SEND_EMAIL"

# 配置邮件处理
[triggers]
crons = ["0 * * * *"] # 每小时运行一次清理任务

# 构建配置
[build]
command = "pnpm run build"

# 静态资源配置
[assets]
binding = "ASSETS"
directory = "frontend/build/client"
